sony/mapray-js

html/index.html
=> change button text and display resource provider in fall demo(#2)

README.md, doc/public/GettingStarted.md, doc/public/MaprayDeveloperGuideMod.md, src/apps/fall/Fall.js, src/apps/next/NextRambler.js, src/apps/turning/turning.js
=> change url of tile server to ssl (#3)

src/mapray/BitVector.js, src/mapray/EntityMaterial.js, src/mapray/GeoMath.js, src/mapray/Primitive.js, src/mapray/Texture.js
=> Changes for future

src/mapray/BitVector.js, src/mapray/Entity.js, src/mapray/EntityMaterial.js, src/mapray/GenericEntity.js, src/mapray/GeoMath.js, src/mapray/Primitive.js, src/mapray/Texture.js
=> Model rotation

.npmignore, .travis.yml, _deploy/scripts/deploy_to_npm_com.sh
*Add npmignore
* add deploying script to server
=> Fixed problem of npm

_deploy/scripts/deploy_to_npm_com.sh
=> Fixed issue with version check

_deploy/firebase.json
Setting cors and cache-control
=> Support cors and cache control

src/mapray/HTTP.js, src/mapray/MaprayApi.js, src/mapray/Resource.js, src/mapray/SceneLoader.js, src/mapray/gltf/Buffer.js, src/mapray/gltf/Context.js, src/mapray/util/Dom.js
- support 3d dataset Apis
- support cloud resource in SceneLoader
=> #146 Pin entity

src/mapray/GeoJSONLoader.js, src/mapray/TextEntity.js
=> fixed warning from UglifyJS

src/mapray/GeoJSONLoader.js, src/mapray/ImageIconEntity.js, src/mapray/PinEntity.js
- GeoJSON Loaderで、altitude_modeコールバックに対応
- PinEntityで、altitude_mode=CLAMPに対応
=> support altitude mode of GeoJSON Loader

src/mapray/GeoJSONLoader.js, src/mapray/GeoMath.js, src/mapray/PolygonEntity.js
Changed extruded property of Polygon
- deleted extruded property
- added extruded_height
Now polygon will be extruded in upper direction. And extruded_height is the amount of the extrusion.
Changed elevation and extruded option of GeoJSONLoader.
- getElevation() has been replaced with getAltitude()
- getExtrudedMode() has been replaced with getExtrudedHeight()
=> changed altitude mode spec

doc/tutorials/09_ChangeGeoJsonFormat.md, doc/tutorials/09_LoadGeoJson.md, doc/tutorials/09_ReadGeoJsonLineProperties.md, doc/tutorials/09_ReadGeoJsonPointProperties.md, doc/tutorials/09_ReadGeoJsonPolygonProperties.md, examples/entity/geojson/ChangeGeoJsonFormat.js, examples/entity/geojson/LoadGeoJSON.js, examples/entity/geojson/ReadGeoJsonLineProperties.js, examples/entity/geojson/ReadGeoJsonPointProperties.js, examples/entity/geojson/ReadGeoJsonPolygonProperties.js, src/apps/next/NextRambler.js
Change API call from API compatibility break at #66
=> Update sample for 071

doc/tutorials/09_ChangeGeoJsonFormat.md, doc/tutorials/09_LoadGeoJson.md, doc/tutorials/09_ReadGeoJsonLineProperties.md, doc/tutorials/09_ReadGeoJsonPointProperties.md, doc/tutorials/09_ReadGeoJsonPolygonProperties.md, examples/entity/geojson/ChangeGeoJsonFormat.js, examples/entity/geojson/ExtrudePolygonProperties.html, examples/entity/geojson/ExtrudePolygonProperties.js, examples/entity/geojson/LoadGeoJSON.js, examples/entity/geojson/ReadGeoJsonLineProperties.js, examples/entity/geojson/ReadGeoJsonPointProperties.js, examples/entity/geojson/ReadGeoJsonPolygonProperties.js, examples/entity/geojson/USGSImageProvider.js, src/apps/next/NextRambler.js
The sample of extruded mode with GeoJSON.
=> Add extruded sample

src/mapray/AttributionController.js, src/mapray/ContainerController.js, src/mapray/LogoController.js, src/mapray/Viewer.js, src/mapray/index.js, src/ui/StandardUIViewer.js, src/ui/index.js
#36
Developers can use this UI engine to introduce general operation methods for map applications into their applications.
=> Support UI engine

src/mapray/TextEntity.js
=> erased unused variable

.travis.yml
=> fixed order or run script

package.json
=> changed dependencies of npm-run-all to only development

src/mapray/Texture.js
=> fixed undefined of Usage.SimpleText

examples/entity/geojson/ExtrudePolygonProperties.js
forgot  that your access token here
=> add access token here, forgot to write

examples/entity/geojson/ChangeGeoJsonFormat.html
File name is invalid and fixed that.
=> change filename to small character

LICENSE
=> update owner company and license year

packages/mapray/src/GeoMath.js, packages/ui/src/StandardUIViewer.js
modified mouse wheel control and right drag control.
=> improved mouse control

debug/uievnets/index.html, debug/uievnets/package.json, debug/uievnets/rollup.config.js, debug/uievnets/src/AppViewer.js, debug/uievnets/src/app.js, debug/uievnets/src/index.js, packages/ui/src/StandardUIViewer.js
Fixed #120 
Re-pullrequest from #121. 
- Fixed the problem of event handler
- Add debug application to use in development
- Convert currect coordinate from window coordinate to element coorinate
- Add Public event handler when get callback from mouse and keyboard events.
=> Fixed events problem

packages/ui/src/StandardUIViewer.js
=> set in variable of each method

packages/mapray/src/animation/Updater.js
Fixed both of the issues in #144.
=> Bugfix animation updater

packages/mapray/.babelrc, packages/mapray/package.json, packages/mapray/src/animation/BindingBlock.js, packages/mapray/src/animation/EasyBindingBlock.js, packages/mapray/tests/animation_tests.js
=> Fix259 animation unbind

packages/mapray/src/GeoJSONLoader.js, packages/mapray/src/HTTP.js, packages/mapray/src/IconLoader.js, packages/mapray/src/ImageIconEntity.js, packages/mapray/src/Loader.js, packages/mapray/src/MaprayApi.js, packages/mapray/src/MaprayApiModel.js, packages/mapray/src/MaprayApiResource.js, packages/mapray/src/Resource.js, packages/mapray/src/SceneLoader.js, packages/mapray/src/index.js, packages/mapray/src/util/Dom.js
=> Refactor resource

packages/mapray/src/GeoMath.js, packages/ui/src/StandardUIViewer.js
implemented for #152 #153 #154
=> Update for camera and geo math

packages/mapray/src/Scene.js
=> bugfix of depth hit test of anchor object

packages/mapray/src/TextEntity.js
=> fixed stroke of TextEntity and minor bug

examples/README.md, examples/animation/AnimePathEasyBinding.html, examples/animation/AnimePathEasyBinding.js, examples/animation/AnimePinCurve.html, examples/animation/AnimePinCurve.js, examples/animation/AnimePinCurveCombo.html, examples/animation/AnimePinCurveCombo.js, examples/animation/AnimePinCurveText.html, examples/animation/AnimePinCurveText.js, examples/animation/AnimePinLinear.html, examples/animation/AnimePinLinear.js, examples/animation/AnimePinStep.html, examples/animation/AnimePinStep.js, examples/animation/CheckInputKeyAndMouse.js, examples/animation/CosCurve.js, examples/animation/CosCurveText.js, examples/animation/CosCurveWithTime.js, examples/animation/README.md
Add some samples for animation.
#142
=> Animation sample

packages/mapray/src/AbstractLineEntity.js, packages/mapray/src/AbstractPointEntity.js, packages/mapray/src/Entity.js, packages/mapray/src/GeoRegion.js, packages/mapray/src/ImageIconEntity.js, packages/mapray/src/ModelEntity.js, packages/mapray/src/PinEntity.js, packages/mapray/src/PolygonEntity.js, packages/mapray/src/TextEntity.js, packages/mapray/src/index.js, packages/mapray/tests/georegion_tests.js
- Add `GeoRegion` class
- Add `Entity#getBounds()`
- Add `AbstractPointEntity` class
=> add getBounds to entity

packages/ui/src/StandardUIViewer.js
=> fix multiplex history url in StandardUIViewer hash

_deploy/scripts/deploy_to_npm_com.sh
=> Change import path and packages names when debug build runs

packages/mapray/src/Resource.js
=> Erased the description in type comment

.gitignore, .travis.yml, apps/fall/package.json, apps/fall/rollup.config.js, apps/next_esm/package.json, apps/next_esm/rollup.config.js, apps/turning/package.json, apps/turning/rollup.config.js, packages/mapray/wasm/rebuild_and_install.sh
- Fixed the problem that a build error occurs due to the dependency with the local build of the application because Emscripten was introduced.
- Fixed CI error
=> Fixed build error for all applications and CI

debug/space/README.md, debug/space/index.html, debug/space/package.json, debug/space/rollup.config.js, debug/space/src/BingMapsImageProvider.js, debug/space/src/Commander.js, debug/space/src/Option.js, debug/space/src/SpaceApp.js, debug/space/src/StatusBar.js, debug/space/src/app.js, debug/space/src/index.js, debug/space/src/utils.js, packages/mapray/src/Layer.js, packages/mapray/src/LayerCollection.js, packages/mapray/src/RenderStage.js, packages/mapray/src/SurfaceMaterial.js, packages/mapray/src/Viewer.js, packages/mapray/src/shader/surface.frag, packages/mapray/src/shader/surface.vert
=> add night layer and capturing view function

packages/mapray/src/ModelEntity.js
add GOCS_MATRIX transform mode to ModelEntity
=> add GOCS_MATRIX transform mode to ModelEntity

packages/mapray/src/FlatDemProvider.js
#202 
Supported Flat, altitude value is zero, supported.
=> support flat dem

packages/ui/src/StandardUIViewer.js
=> ref #205, Support to switch visibility of entity and ground in ui packge

packages/mapray/src/index.js
=> exported flatdem provider

.github/workflows/npm_release.yml, .github/workflows/npm_release_prerelease.yml
=> fixed publising method

packages/ui/src/StandardUIViewer.ts
Fixed a bug that caused the URL update function to stop.
=> fix-bug-of-url-update

.github/workflows/purejs_deploy_release_and_prerelease.yml
=> Use google-github-actions/auth@v1 instead of credentials
